M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu21.04.1} date Tue 04 Jan 2022 02:06:46 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-04T14:06:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu21.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0600
%
G90
G05
T1
X6.4008Y-3.1883
X6.4008Y-3.9883
T0
M30
